import { WallpaperSlot, FitMode, ImageFilters } from '../types/wallpaper';

export class WallpaperService {
  // Generates CSS filter string for preview and canvas rendering
  public static getCssFilterString(filters?: ImageFilters): string {
    if (!filters) return 'none';
    const parts: string[] = [];
    if (filters.brightness !== 100) parts.push(`brightness(${filters.brightness}%)`);
    if (filters.contrast !== 100) parts.push(`contrast(${filters.contrast}%)`);
    if (filters.saturation !== 100) parts.push(`saturate(${filters.saturation}%)`);
    if (filters.blur > 0) parts.push(`blur(${filters.blur}px)`);
    if (filters.hueRotate !== 0) parts.push(`hue-rotate(${filters.hueRotate}deg)`);
    if (filters.grayscale > 0) parts.push(`grayscale(${filters.grayscale}%)`);
    if (filters.sepia > 0) parts.push(`sepia(${filters.sepia}%)`);
    return parts.length > 0 ? parts.join(' ') : 'none';
  }

  // Returns CSS background styles based on FitMode
  public static getFitModeStyles(fitMode: FitMode): React.CSSProperties {
    switch (fitMode) {
      case 'fill':
        return {
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        };
      case 'fit':
        return {
          backgroundSize: 'contain',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          backgroundColor: '#0a0a0c',
        };
      case 'stretch':
        return {
          backgroundSize: '100% 100%',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        };
      case 'tile':
        return {
          backgroundSize: 'auto',
          backgroundPosition: 'top left',
          backgroundRepeat: 'repeat',
        };
      case 'center':
        return {
          backgroundSize: 'auto',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          backgroundColor: '#0a0a0c',
        };
      case 'span':
        return {
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        };
      default:
        return {
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        };
    }
  }

  // Generate Windows PowerShell snippet for setting wallpaper natively
  public static generatePowerShellCommand(slot: WallpaperSlot): string {
    return `# Windows PowerShell script generated by Wallpaper Selector App
$code = @'
using System;
using System.Runtime.InteropServices;
public class Wallpaper {
    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    public static extern int SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
}
'@
Add-Type $code
[Wallpaper]::SystemParametersInfo(0x0014, 0, "${slot.url}", 0x01 | 0x02)
Write-Host "Wallpaper Slot ${slot.slotNumber} ('${slot.title}') applied successfully!" -ForegroundColor Green
`;
  }
}
