import { WallpaperSlot, PresetPack, AppSettings, HotkeyConfig, AutoRotateConfig } from '../types/wallpaper';

export const DEFAULT_FILTERS = {
  brightness: 100,
  contrast: 100,
  saturation: 100,
  blur: 0,
  hueRotate: 0,
  grayscale: 0,
  sepia: 0,
  vignette: 0,
};

export const INITIAL_WALLPAPER_SLOTS: WallpaperSlot[] = [
  {
    id: 'slot-1-dolomites',
    slotNumber: 1,
    title: 'Alpine Meadow & Dolomite Peaks',
    url: 'https://images.pexels.com/photos/609554/pexels-photo-609554.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
    thumbnailUrl: 'https://images.pexels.com/photos/609554/pexels-photo-609554.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
    sourceType: 'preset',
    resolution: '3840 × 2160 (4K)',
    fileSize: '4.8 MB',
    category: 'Nature',
    author: 'Mauricio Artieda',
    authorUrl: 'https://www.pexels.com/@martieda',
    fitMode: 'fill',
    targetMonitor: 'all',
    filters: { ...DEFAULT_FILTERS },
    addedAt: Date.now() - 100000,
    isActive: true, // Slot 1 active by default
  },
  {
    id: 'slot-2-cyberpunk',
    slotNumber: 2,
    title: 'Futuristic Cyberpunk Neon Skyline',
    url: 'https://images.pexels.com/photos/18545010/pexels-photo-18545010.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
    thumbnailUrl: 'https://images.pexels.com/photos/18545010/pexels-photo-18545010.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
    sourceType: 'preset',
    resolution: '7680 × 4320 (8K)',
    fileSize: '6.2 MB',
    category: 'Cyberpunk',
    author: 'Pachon in Motion',
    authorUrl: 'https://www.pexels.com/@pachon-in-motion-426015731',
    fitMode: 'fill',
    targetMonitor: 'all',
    filters: { ...DEFAULT_FILTERS, saturation: 110, contrast: 105 },
    addedAt: Date.now() - 90000,
    isActive: false,
  },
  {
    id: 'slot-3-fluid',
    slotNumber: 3,
    title: 'Vibrant 3D Fluid Hologram Waves',
    url: 'https://images.pexels.com/photos/33797643/pexels-photo-33797643.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
    thumbnailUrl: 'https://images.pexels.com/photos/33797643/pexels-photo-33797643.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
    sourceType: 'preset',
    resolution: '3840 × 2160 (4K)',
    fileSize: '3.9 MB',
    category: 'Abstract',
    author: 'Steve A Johnson',
    authorUrl: 'https://www.pexels.com/@steve',
    fitMode: 'fill',
    targetMonitor: 'all',
    filters: { ...DEFAULT_FILTERS },
    addedAt: Date.now() - 80000,
    isActive: false,
  },
  {
    id: 'slot-4-space',
    slotNumber: 4,
    title: 'Deep Space Cosmic Nebula & Stars',
    url: 'https://images.pexels.com/photos/3180831/pexels-photo-3180831.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
    thumbnailUrl: 'https://images.pexels.com/photos/3180831/pexels-photo-3180831.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
    sourceType: 'preset',
    resolution: '5000 × 4000 (5K)',
    fileSize: '5.1 MB',
    category: 'Space',
    author: 'Frank Cone',
    authorUrl: 'https://www.pexels.com/@frank-cone-140140',
    fitMode: 'fill',
    targetMonitor: 'all',
    filters: { ...DEFAULT_FILTERS, contrast: 110 },
    addedAt: Date.now() - 70000,
    isActive: false,
  },
  {
    id: 'slot-5-sunset-forest',
    slotNumber: 5,
    title: 'Pine Forest at Golden Sunset',
    url: 'https://images.pexels.com/photos/592077/pexels-photo-592077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
    thumbnailUrl: 'https://images.pexels.com/photos/592077/pexels-photo-592077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
    sourceType: 'preset',
    resolution: '3648 × 2736 (4K)',
    fileSize: '4.3 MB',
    category: 'Nature',
    author: 'Katja',
    authorUrl: 'https://www.pexels.com/@katja-79053',
    fitMode: 'fill',
    targetMonitor: 'all',
    filters: { ...DEFAULT_FILTERS },
    addedAt: Date.now() - 60000,
    isActive: false,
  },
  {
    id: 'slot-6-las-vegas',
    slotNumber: 6,
    title: 'Metropolis Neon Architecture',
    url: 'https://images.pexels.com/photos/14044350/pexels-photo-14044350.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
    thumbnailUrl: 'https://images.pexels.com/photos/14044350/pexels-photo-14044350.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
    sourceType: 'preset',
    resolution: '6000 × 4000 (6K)',
    fileSize: '5.8 MB',
    category: 'Cyberpunk',
    author: 'Ricardo Olvera',
    authorUrl: 'https://www.pexels.com/@ricardo-olvera-225422504',
    fitMode: 'fill',
    targetMonitor: 'all',
    filters: { ...DEFAULT_FILTERS, brightness: 105, saturation: 115 },
    addedAt: Date.now() - 50000,
    isActive: false,
  },
];

export const PRESET_PACKS: PresetPack[] = [
  {
    id: 'pack-nature-sanctuary',
    name: 'Nature Sanctuary 4K',
    description: 'Serene mountain peaks, lush valleys, morning fog, and twilight ranges.',
    category: 'Nature',
    wallpapers: [
      {
        title: 'Alpine Meadow & Dolomite Peaks',
        url: 'https://images.pexels.com/photos/609554/pexels-photo-609554.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/609554/pexels-photo-609554.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '3840 × 2160',
        fileSize: '4.8 MB',
        category: 'Nature',
        author: 'Mauricio Artieda',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Pine Forest Golden Hour',
        url: 'https://images.pexels.com/photos/592077/pexels-photo-592077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/592077/pexels-photo-592077.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '3648 × 2736',
        fileSize: '4.3 MB',
        category: 'Nature',
        author: 'Katja',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Foggy Mountain Peaks at Dawn',
        url: 'https://images.pexels.com/photos/629159/pexels-photo-629159.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/629159/pexels-photo-629159.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '5472 × 3648',
        fileSize: '5.4 MB',
        category: 'Nature',
        author: 'Eberhard Grossgasteiger',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Lush Green Mountain Valley',
        url: 'https://images.pexels.com/photos/1679815/pexels-photo-1679815.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/1679815/pexels-photo-1679815.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '5760 × 3840',
        fileSize: '5.9 MB',
        category: 'Nature',
        author: 'Markus Spiske',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Dramatic Alpine Clouds',
        url: 'https://images.pexels.com/photos/3224115/pexels-photo-3224115.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/3224115/pexels-photo-3224115.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '4656 × 3096',
        fileSize: '4.6 MB',
        category: 'Nature',
        author: 'Hert Niks',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Twilight Mountain Silhouette',
        url: 'https://images.pexels.com/photos/1809644/pexels-photo-1809644.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/1809644/pexels-photo-1809644.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '5472 × 3648',
        fileSize: '4.9 MB',
        category: 'Nature',
        author: 'Simon Rizzi',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
    ],
  },
  {
    id: 'pack-cyberpunk-neon',
    name: 'Cyberpunk Neon 2077',
    description: 'Electric neon lights, futuristic metropolis reflections, and dark night aesthetics.',
    category: 'Cyberpunk',
    wallpapers: [
      {
        title: 'Futuristic Red Glow Skyline',
        url: 'https://images.pexels.com/photos/18545010/pexels-photo-18545010.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/18545010/pexels-photo-18545010.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '7680 × 4320',
        fileSize: '6.2 MB',
        category: 'Cyberpunk',
        author: 'Pachon in Motion',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Chongqing Futuristic Riverfront',
        url: 'https://images.pexels.com/photos/32660203/pexels-photo-32660203.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/32660203/pexels-photo-32660203.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '5036 × 3359',
        fileSize: '5.2 MB',
        category: 'Cyberpunk',
        author: 'Yiyang Liu',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Cyberpunk Alley Neon Signage',
        url: 'https://images.pexels.com/photos/28122495/pexels-photo-28122495.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/28122495/pexels-photo-28122495.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '4928 × 2776',
        fileSize: '4.7 MB',
        category: 'Cyberpunk',
        author: 'Tu Dou',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Midnight Las Vegas Architecture',
        url: 'https://images.pexels.com/photos/14044350/pexels-photo-14044350.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/14044350/pexels-photo-14044350.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '6000 × 4000',
        fileSize: '5.8 MB',
        category: 'Cyberpunk',
        author: 'Ricardo Olvera',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Cyberpunk Shadow Alley',
        url: 'https://images.pexels.com/photos/17195067/pexels-photo-17195067.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/17195067/pexels-photo-17195067.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '3840 × 2160',
        fileSize: '3.8 MB',
        category: 'Cyberpunk',
        author: 'Kaio Ryan',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Electric Skyscraper Pulse',
        url: 'https://images.pexels.com/photos/14976666/pexels-photo-14976666.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/14976666/pexels-photo-14976666.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '4642 × 2164',
        fileSize: '4.4 MB',
        category: 'Cyberpunk',
        author: 'Ernest Busalpa',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
    ],
  },
  {
    id: 'pack-abstract-fluid',
    name: '3D Fluid & Windows 11 Fluent Waves',
    description: 'Smooth acrylic gradients, flowing silk ribbons, and modern abstract art.',
    category: 'Abstract',
    wallpapers: [
      {
        title: 'Purple & Magenta 3D Ribbon',
        url: 'https://images.pexels.com/photos/33797643/pexels-photo-33797643.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/33797643/pexels-photo-33797643.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '6000 × 4000',
        fileSize: '3.9 MB',
        category: 'Abstract',
        author: 'Steve A Johnson',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Cobalt & Violet Wave Dynamic',
        url: 'https://images.pexels.com/photos/34939150/pexels-photo-34939150.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/34939150/pexels-photo-34939150.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '6000 × 4000',
        fileSize: '4.2 MB',
        category: 'Abstract',
        author: 'Steve A Johnson',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Warm Gradient Ember Flow',
        url: 'https://images.pexels.com/photos/28628485/pexels-photo-28628485.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/28628485/pexels-photo-28628485.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '6000 × 2524',
        fileSize: '3.7 MB',
        category: 'Abstract',
        author: 'Steve A Johnson',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Luminescent Silk Swirl',
        url: 'https://images.pexels.com/photos/29101877/pexels-photo-29101877.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/29101877/pexels-photo-29101877.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '9000 × 6000',
        fileSize: '6.5 MB',
        category: 'Abstract',
        author: 'Steve A Johnson',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Cosmic Royal Blue Ripple',
        url: 'https://images.pexels.com/photos/29708308/pexels-photo-29708308.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/29708308/pexels-photo-29708308.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '7680 × 4320',
        fileSize: '5.3 MB',
        category: 'Abstract',
        author: 'Steve A Johnson',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Prismatic Fluid Harmony',
        url: 'https://images.pexels.com/photos/13568046/pexels-photo-13568046.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/13568046/pexels-photo-13568046.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '5760 × 3240',
        fileSize: '4.8 MB',
        category: 'Abstract',
        author: 'Steve A Johnson',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
    ],
  },
  {
    id: 'pack-deep-space',
    name: 'Cosmos & Deep Space 4K',
    description: 'Breathtaking nebulas, Milky Way galaxies, star clusters, and deep space panoramas.',
    category: 'Space',
    wallpapers: [
      {
        title: 'Deep Space Nebula Glow',
        url: 'https://images.pexels.com/photos/3180831/pexels-photo-3180831.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/3180831/pexels-photo-3180831.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '5000 × 4000',
        fileSize: '5.1 MB',
        category: 'Space',
        author: 'Frank Cone',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Milky Way Galaxy Arc',
        url: 'https://images.pexels.com/photos/2538107/pexels-photo-2538107.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/2538107/pexels-photo-2538107.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '6000 × 4000',
        fileSize: '5.7 MB',
        category: 'Space',
        author: 'Adrien Olichon',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Cyan & Violet Starfield',
        url: 'https://images.pexels.com/photos/3607542/pexels-photo-3607542.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/3607542/pexels-photo-3607542.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '4800 × 2700',
        fileSize: '4.5 MB',
        category: 'Space',
        author: 'Frank Cone',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Lagoon Nebula Deep View',
        url: 'https://images.pexels.com/photos/18500331/pexels-photo-18500331.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/18500331/pexels-photo-18500331.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '5087 × 3391',
        fileSize: '5.3 MB',
        category: 'Space',
        author: 'Eclipse Chasers',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Interstellar Gas & Stellar Nursery',
        url: 'https://images.pexels.com/photos/20881655/pexels-photo-20881655.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/20881655/pexels-photo-20881655.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '4265 × 3275',
        fileSize: '4.6 MB',
        category: 'Space',
        author: 'Robert Gruszecki',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
      {
        title: 'Crimson & Cobalt Celestial Sky',
        url: 'https://images.pexels.com/photos/4233216/pexels-photo-4233216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1440&w=2560',
        thumbnailUrl: 'https://images.pexels.com/photos/4233216/pexels-photo-4233216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=500',
        sourceType: 'preset',
        resolution: '4800 × 2700',
        fileSize: '4.8 MB',
        category: 'Space',
        author: 'Frank Cone',
        fitMode: 'fill',
        targetMonitor: 'all',
        filters: { ...DEFAULT_FILTERS },
      },
    ],
  },
];

export const DEFAULT_APP_SETTINGS: AppSettings = {
  theme: 'mica-dark',
  accentColor: '#0078D4',
  startWithWindows: true,
  minimizeToTray: true,
  showDesktopFlyoutOnHotkey: true,
  soundEffects: true,
  hardwareAcceleration: true,
  confirmBeforeSlotDelete: false,
  cacheLocation: 'C:\\Users\\User\\AppData\\Local\\WallpaperSelectorApp\\Thumbnails',
  maxCacheSizeMb: 500,
  currentMonitorCount: 2,
  telemetryEnabled: false,
  celebrationEnabled: true,
};

export const DEFAULT_HOTKEYS: HotkeyConfig = {
  openPicker: 'Win+Alt+W',
  nextSlot: 'Win+Alt+Right',
  prevSlot: 'Win+Alt+Left',
  slot1: 'Win+Alt+1',
  slot2: 'Win+Alt+2',
  slot3: 'Win+Alt+3',
  slot4: 'Win+Alt+4',
  slot5: 'Win+Alt+5',
  slot6: 'Win+Alt+6',
  enableGlobalHotkeys: true,
};

export const DEFAULT_AUTO_ROTATE: AutoRotateConfig = {
  enabled: false,
  intervalMinutes: 15,
  shuffle: false,
  pauseOnBattery: true,
  pauseWhenFullscreenApp: true,
  timeOfDayTheme: false,
  daySlot: 1,
  nightSlot: 4,
  transitionEffect: 'fade',
  transitionDurationMs: 600,
};
